#! /bin/bash

TAG="" 

# update qcacld
git remote add qcacld https://source.codeaurora.org/quic/la/platform/vendor/qcom-opensource/wlan/qcacld-3.0
git fetch qcacld $TAG
git merge -X subtree=drivers/staging/qcacld-3.0 --no-commit FETCH_HEAD
git commit -m "MERGED UPDATE: qcacld into $TAG" --signoff

# update fwapi
git remote add fw-api https://source.codeaurora.org/quic/la/platform/vendor/qcom-opensource/wlan/fw-api
git fetch fw-api $TAG
git merge -X subtree=drivers/staging/fw-api --no-commit FETCH_HEAD
git commit -m "MERGED UPDATE: fw-api into $TAG" --signoff

# update qca-host-wifi-cmn
git remote add qca-wifi-host-cmn https://source.codeaurora.org/quic/la/platform/vendor/qcom-opensource/wlan/qca-wifi-host-cmn
git fetch qca-wifi-host-cmn $TAG
git merge -X subtree=drivers/staging/qca-wifi-host-cmn --no-commit FETCH_HEAD
git commit -m "MERGED UPDATE: qca-host-wifi-cmn into $TAG" --signoff

# push
git push
