name: initial merge qcacld

on:
  push:
  schedule:
    - cron: '0 0 * * 0,4'

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Setup
      run: |
        sudo apt-get update
        sudo apt-get install -y git
    - name: acc github
      run: |
        git config --global user.name "${GITHUB_USER}"
        git config --global user.email "${GITHUB_EMAIL}"
    - name: start
      run: |
        bash merged
    - name: push
      run: |
        git push https://"${GITHUB_USER}":"${GITHUB_TOKEN}"@github.com/"${GITHUB_USER}"/"${REPO}"
      env:
        GITHUB_EMAIL: $GMAIL
        GITHUB_USER: $USERNAME
        REPO: $REPO
        TAG: $TAG
