name: initial merge qcacld

on:
  push:
  schedule:
    - cron: '0 0 * * 0,4'

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Setup
      run: |
        sudo apt-get update
        sudo apt-get install -y git
    - name: clone source and open dir
      run: |
        git clone https://github.com/Baka-Project/Baka-Msm-4.14.git
        cd Baka-Msm-4.14
    - name: acc github
      run: |
        git config --global user.name "${GITHUB_USER}"
        git config --global user.email "${GITHUB_EMAIL}"
    - name: start
      run: |
        curl https://raw.githubusercontent.com/vcyzteen/Lazy-Merged/main/mergedXupdate | bash
    - name: push
      run: |
        git push https://"${GITHUB_USER}":"${GITHUB_TOKEN}"@github.com/Baka-Project/Baka-Msm-4.14.git baka-4.14
      env:
        GITHUB_EMAIL: ${{ secrets.GMAIL }}
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        GITHUB_USER: ${{ secrets.USERNAME }}
